CREATE TABLE TRANSACTIONS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    AMOUNT NUMBER(10, 2) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE
);

-- Inserção de exemplo
INSERT INTO TRANSACTIONS (TITLE, AMOUNT) VALUES ('Initial transaction', 100.00);

COMMIT;
